/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.me.qpad;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int qpad_icon=0x7f020000;
    }
    public static final class id {
        public static final int bExit=0x7f050006;
        public static final int bHighScores=0x7f050005;
        public static final int bNew=0x7f050004;
        public static final int closeGame=0x7f050001;
        public static final int main_menu=0x7f050003;
        public static final int submit=0x7f050002;
        public static final int txtEntry=0x7f050007;
        public static final int txtGameOver=0x7f050000;
    }
    public static final class layout {
        public static final int finish=0x7f030000;
        public static final int finish_high=0x7f030001;
        public static final int high_scores=0x7f030002;
        public static final int list_item=0x7f030003;
        public static final int main=0x7f030004;
        public static final int submit_high=0x7f030005;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int exit=0x7f040003;
        public static final int finished_button=0x7f040007;
        public static final int finished_high_button_1=0x7f040008;
        public static final int finished_high_button_2=0x7f040009;
        public static final int finished_high_text=0x7f04000b;
        public static final int finished_high_title=0x7f04000a;
        public static final int finished_text=0x7f040006;
        public static final int finished_title=0x7f040005;
        public static final int high_scores=0x7f040004;
        public static final int newgame=0x7f040002;
        public static final int title=0x7f040001;
    }
}
